SELECT * FROM MEMBER
WHERE 1 = 0;

-- MEMBER 테이블을 복제해서 MEMBER_S 테이블 생성

-- 테이블 컬럼 복제(NOT NULL 제약조건만 복제됨)
CREATE TABLE MEMBER_S
AS SELECT * FROM MEMBER
WHERE 1 = 0;

-- 컬럼 기본값 지정
ALTER TABLE MEMBER_S
MODIFY ENROLL_DT DEFAULT SYSDATE;

ALTER TABLE MEMBER_S
MODIFY SECESSION_FL DEFAULT 'N';

-- PK 제약조건 추가
ALTER TABLE MEMBER_S
ADD CONSTRAINT MEMBER_S_PK PRIMARY KEY(MEMBER_NO);


-- CHECK 제약조건 추가
ALTER TABLE MEMBER_S
ADD CONSTRAINT MEMBER_S_CHK CHECK(SECESSION_FL IN('Y', 'N'));


-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO_S NOCACHE;


-- 샘플데이터 추가
INSERT INTO MEMBER_S VALUES(
	SEQ_MEMBER_NO_S.NEXTVAL,
	'test01@naver.com',
	'pass01!',
	'테스트1',
	'01012341234',
	DEFAULT, DEFAULT, DEFAULT, DEFAULT
);



-- 아이디, 비밀번호가 일치하는 회원의 전화번호 조회
-- 단, 정상회원만
SELECT MEMBER_TEL FROM MEMBER_S
WHERE MEMBER_EMAIL = 'test01@naver.com'
AND MEMBER_PW = 'pass01!'
AND SECESSION_FL = 'N';