CREATE TABLE CHAT_ROOM (
	CHAT_ROOM_NO	NUMBER	PRIMARY KEY,
	TITLE	VARCHAR2(200)	NOT NULL,
	STATUS	CHAR(1)	DEFAULT 'Y' CHECK(STATUS IN('Y','N')),
	MEMBER_NO NUMBER REFERENCES MEMBER_S
);


COMMENT ON COLUMN CHAT_ROOM.CHAT_ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_ROOM.TITLE IS '채팅방제목';
COMMENT ON COLUMN CHAT_ROOM.STATUS IS '채팅방상태(정상:Y, 삭제:N)';
COMMENT ON COLUMN CHAT_ROOM.MEMBER_NO IS '회원번호(방 개설자)';


CREATE TABLE CHAT_MESSAGE (
	CM_NO	NUMBER	PRIMARY KEY,
	MESSAGE	VARCHAR2(4000)	NOT NULL,
	CREATE_DT	DATE DEFAULT SYSDATE,
	CHAT_ROOM_NO NUMBER	REFERENCES CHAT_ROOM,
	MEMBER_NO	NUMBER REFERENCES MEMBER_S
);

COMMENT ON COLUMN CHAT_MESSAGE.CM_NO IS '채팅메세지번호';
COMMENT ON COLUMN CHAT_MESSAGE.MESSAGE IS '작성한 채팅 메세지';
COMMENT ON COLUMN CHAT_MESSAGE.CREATE_DT IS '메세지 작성 시간';
COMMENT ON COLUMN CHAT_MESSAGE.CHAT_ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_MESSAGE.MEMBER_NO IS '회원번호';


CREATE TABLE CHAT_ROOM_JOIN (
	MEMBER_NO NUMBER REFERENCES MEMBER_S,
	CHAT_ROOM_NO NUMBER REFERENCES CHAT_ROOM,
    PRIMARY KEY(MEMBER_NO, CHAT_ROOM_NO)
);


COMMENT ON COLUMN CHAT_ROOM_JOIN.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN CHAT_ROOM_JOIN.CHAT_ROOM_NO IS '채팅방번호';

CREATE SEQUENCE SEQ_CR_NO;
CREATE SEQUENCE SEQ_CM_NO;

COMMIT;